### ISSUE TITLE
Using a variable for Query string not working

### ISSUE THREAD

**Issue by xzfvictor** [elgs/jsonql#10]
Hi @elgs 

One more issue:
If I replace the query string ("name='elgs'") with a variable, it doesn't return result.

string := "\"name=" + "'elgs'"
fmt.Println(parser.Query(string )) 

// output [] <nil>

**Comment by elgs** [comment]
I just had a test, and it seems it worked for me.

**Comment by xzfvictor** [comment]
Please check here. @elgs 
https://play.golang.org/p/QhA1gcFCoct

**Comment by elgs** [comment]
Check this:
https://play.golang.org/p/wG1dsLb8Uw7

**Comment by xzfvictor** [comment]
ah.. my bad!

Thanks again! @elgs
