### ISSUE TITLE
Compare a bool

### ISSUE THREAD

**Issue by Eun** [elgs/jsonql#6]
Saying you have a json payload like this: 
```json
[
{
   "Name": "Joe",
   "IsMale": true
},
{
   "Name": "Alice",
   "IsMale": false
}
]
```

The query `IsMale=true` gives no results.

Any idea?

**Comment by elgs** [comment]
I confirm this is a problem. Thanks. I will fix it.

**Comment by elgs** [comment]
Hopefully the problem has been fixed. Would you please try `go get -u https://github.com/elgs/jsonql` and let me if it works for you? Thank you!

**Comment by Eun** [comment]
Yes works thank you
