### ISSUE TITLE
Unable to query []string

### ISSUE THREAD

**Issue by xzfvictor** [elgs/jsonql#9]
It appears that I can not query, e.g. "skills" in the example data.

**Comment by elgs** [comment]
Can you please show me you code that doesn’t work? Thanks.

**Comment by xzfvictor** [comment]
@elgs 

package main

import (
	"fmt"
	"github.com/elgs/jsonql"
)

var jsonString = `
[
  {
    "name": "elgs",
    "gender": "m",
    "age": 35,
    "skills": [
      "Golang",
      "Java",
      "C"
    ]
  },
  {
    "name": "enny",
    "gender": "f",
    "age": 36,
    "hobby": null,
    "skills": [
      "IC",
      "Electric design",
      "Verification"
    ]
  },
  {
    "name": "sam",
    "gender": "m",
    "age": 1,
    "hobby": "dancing",
    "skills": [
      "Eating",
      "Sleeping",
      "Crawling"
    ]
  }
]
`

func main() {
	parser, err := jsonql.NewStringQuery(jsonString)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(parser.Query("skills='Eating'"))
}

output: [] <nil>

**Comment by xzfvictor** [comment]
Am I using it correctly for query "skills"? Thanks!

**Comment by elgs** [comment]
Please run `go get -u github.com/elgs/jsonql` again and try:

```
fmt.Println(parser.Query("skills contains 'Eating'"))
```

**Comment by xzfvictor** [comment]
Yeah, it's working now!

Brilliant! @elgs
